### ISSUE TITLE
How It works?

### ISSUE THREAD

**Issue by 1995parham** [4lie/nats-health-check#7]
Here we are going to discuss about the functionality of this project to monitor our NATS/NATS Streaming servers.

**Comment by RashadAnsari** [comment]
> The monitoring package consumes NATS messages then provides Prometheus metrics.

@1995parham @parsaaes  Which metric should we have?

Isn't it better that we run nats-health-check binary after each deploy and get 0 or 1 exit code and using these we can find that our cluster is healthy after our deploy or not? and in each of our applications, that for example consume some event from NATS we have Prometheus metrics for finding that we don't receive any message like now that we use Kafka.

I mean that we just use this application as a health check after deploy, not continue checking. and we can do continues checking in each of our applications using NATS.

What are your opinions? @1995parham @parsaaes

**Comment by 1995parham** [comment]
Yes, It can do this too with a command. It also can have command for monitoring with Prometheus in case we want it in the future. For this usage, it starts, sends, and then consumes. So we can summarize its features as follow:

- Test Mode: In this mode, it only tests cluster with basic functionality
- Monitor Mode: In this mode, it monitors a topic constantly and reports its metrics.

**Comment by RashadAnsari** [comment]
> Yes, It can do this too with a command. It also can have command for monitoring with Prometheus in case we want it in the future. For this usage, it starts, sends, and then consumes. So we can summarize its features as follow:
> 
> * Test Mode: In this mode, it only tests cluster with basic functionality
> * Monitor Mode: In this mode, it monitors a topic constantly and reports its metrics.

I am totaly agree with you. 👍
